"""Planner StateGraph workflow module.

Encapsulates planner model/agent state in a LangGraph StateGraph, compiled with
a checkpointer and invoked via streaming using thread configurations.
"""

from __future__ import annotations

import json
from collections.abc import AsyncIterator
from enum import StrEnum
from typing import Annotated, Any, Optional

import uuid
import structlog
from deepagents import create_deep_agent
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import (
    AIMessage,
    AnyMessage,
    BaseMessage,
    HumanMessage,
    convert_to_messages,
)
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.graph import END, StateGraph, add_messages
from langgraph.graph.state import CompiledStateGraph
from pydantic import BaseModel

from agents.filesystem_backend import default_filesystem_backend
from agents.loop_agent import create_loop_agent
from agents.prompts import (
    get_evaluator_prompt,
    get_planner_prompt,
)
from application.planner_service import PlannerService
from domain.planner_models import Planner
from persistence.database import SessionFactory
from agents.planner_middleware import AgentContext, PlannerMode
from agents.planner_tools import get_plan_creation_tools, get_plan_evaluator_tools
from agents.tools import get_register_company_tool

logger = structlog.get_logger(__name__)

class Decision(StrEnum):
    ACCEPT = "accept"
    RETRY = "retry"


class NodeName(StrEnum):
    PREP_PLANNER = "prep_planner"
    PLANNER = "planner"
    SYNC_PLANNER_OUTPUT = "sync_planner_output"
    PREP_EVALUATOR = "prep_evaluator"
    EVALUATOR = "evaluator"
    PARSE_EVALUATOR_OUTPUT = "parse_evaluator_output"
    INCREMENT_RETRY = "increment_retry"


class Evaluation(BaseModel):
    feedback: str
    decision: Decision


class AgentState(BaseModel):
    task: str = None
    evaluation: Optional[Evaluation] = None
    retries: int = 0
    plan: Optional[Planner] = None
    planner_chat: list[AnyMessage] = []
    evaluator_chat: list[AnyMessage] = []
    messages: list[AnyMessage] = []
    structured_response: Any = None


def increment_retry(state: AgentState) -> AgentState:
    state.retries += 1

    logger.info(
        "executing_node",
        node_name=NodeName.INCREMENT_RETRY,
        attempt=state.retries,
    )
    feedback = state.evaluation.feedback if state.evaluation else "Please refine and complete the execution plan."
    feedback_msg = HumanMessage(
        content=f"""
EVALUATOR REVIEW — REVISION REQUIRED
Attempt: {state.retries}

The following feedback was generated by the Evaluator after reviewing the current execution plan.

Evaluator Feedback:
{feedback}
"""
    )
    state.planner_chat.append(feedback_msg)
    return state


MAX_RETRIES = 5


def replan_router(state: AgentState) -> str:
    if state.evaluation and state.evaluation.decision == Decision.ACCEPT:
        logger.info(
            "router_decision",
            decision=END,
            reason="Evaluation accepted",
        )
        return END

    if state.retries >= MAX_RETRIES:
        logger.info(
            "router_decision",
            decision=END,
            reason=f"Reached max retries ({MAX_RETRIES})",
        )
        return END

    logger.info(
        "router_decision",
        decision=NodeName.INCREMENT_RETRY,
        reason="Evaluation requested retry",
    )
    return NodeName.INCREMENT_RETRY


def create_planner_graph(
    model: BaseChatModel,
    checkpointer: BaseCheckpointSaver | None = None,
    store: Any = None,
    effort_prefix: str = "",
    strategy_id: str | None = None,
    session: Any | None = None,
) -> CompiledStateGraph:
    """Build a StateGraph(AgentState) graph using native subgraph nodes and isolated state channels.

    Compiles planner and evaluator subgraphs directly into the parent StateGraph.
    Checkpoints are natively tracked across hierarchical namespaces for seamless continuation.
    """
    # 1. Instantiate Planner & Evaluator Subgraph Agents
    reg_tools = get_register_company_tool(session, strategy_id, effort_prefix)
    creation_tools = get_plan_creation_tools(session, strategy_id, effort_prefix)
    planner_subgraph = create_loop_agent(
        name="Planner Agent",
        model=model,
        tools=creation_tools + reg_tools,
        system_prompt=get_planner_prompt(),
        session=session,
        strategy_id=strategy_id,
        checkpointer=checkpointer,
        store=store,
        context_schema=AgentContext,
        backend=default_filesystem_backend(),
    )

    eval_tools = get_plan_evaluator_tools(session, strategy_id, effort_prefix)
    evaluator_subgraph = create_loop_agent(
        name="Evaluator Agent",
        model=model,
        system_prompt=get_evaluator_prompt(),
        tools=eval_tools + creation_tools + reg_tools,
        session=session,
        strategy_id=strategy_id,
        checkpointer=checkpointer,
        store=store,
        context_schema=AgentContext,
        response_format=Evaluation,
        backend=default_filesystem_backend(),
    )

    async def run_planner_node(state: AgentState, config: Optional[RunnableConfig] = None) -> dict:
        return await planner_subgraph.ainvoke(
            state,
            context=AgentContext(mode=PlannerMode.PLAN),
            config=config,
        )

    async def run_evaluator_node(state: AgentState, config: Optional[RunnableConfig] = None) -> dict:
        return await evaluator_subgraph.ainvoke(
            state,
            context=AgentContext(mode=PlannerMode.EVALUATE),
            config=config,
        )

    # 2. State Transformation Nodes
    def prep_planner(state: AgentState) -> AgentState:
        task = """Create a detailed execution plan to identify and select one company based on the defined sales strategy.

First, consult the Sales Manager to understand:

* The sales strategy being followed.
* The target customer profile (ICP).
* The product/service being sold.
* The value proposition and positioning.
* The specific strategy we are trying to validate.

Based on this information, prepare an execution plan for identifying and selecting one company that matches the strategy. The goal is to use this plan as a test case to determine whether the defined sales strategy makes sense and can successfully identify a suitable prospect.
"""
        logger.info(
            "executing_node",
            node_name=NodeName.PREP_PLANNER,
        )
        state.task = task
        if not state.planner_chat:
            state.planner_chat = [HumanMessage(content=task)]

        state.messages = state.planner_chat
        return state

    async def sync_planner_output(
        state: AgentState, config: Optional[RunnableConfig] = None
    ) -> AgentState:
        logger.info(
            "executing_node",
            node_name=NodeName.SYNC_PLANNER_OUTPUT,
        )
        plan_obj = None
        if effort_prefix:
            try:
                async with SessionFactory() as session:
                    svc = PlannerService(session)
                    plan_obj = await svc.get_plan(effort_prefix)
            except Exception as err:
                logger.warning(
                    "planner_graph_sync_db_warning",
                    effort_prefix=effort_prefix,
                    error=str(err),
                )

        state.planner_chat = state.messages
        state.plan = plan_obj
        state.messages = []
        return state

    def prep_evaluator(state: AgentState) -> AgentState:
        logger.info(
            "executing_node",
            node_name=NodeName.PREP_EVALUATOR,
        )
        plan_json = state.plan.get_plan() if state.plan else "No structured plan."

        if state.evaluator_chat:
            state.evaluator_chat.append(HumanMessage(content=f"""
Re-evaluate the execution plan below after the Planner has addressed your previous feedback.

Task:
{state.task}

Updated Execution Plan:
{plan_json}
"""))
        else:
            state.evaluator_chat = [HumanMessage(content=f"""
Evaluate the following execution plan for the given task.

Task:
{state.task}

Execution Plan:
{plan_json}

""")]
        state.messages = state.evaluator_chat
        return state

    def parse_evaluator_output(state: AgentState) -> AgentState:
        logger.info(
            "executing_node",
            node_name=NodeName.PARSE_EVALUATOR_OUTPUT,
        )
        state.evaluator_chat = state.messages
        state.evaluation = state.structured_response or Evaluation(
            feedback="Plan evaluation complete.", decision=Decision.ACCEPT
        )
        state.messages = []
        return state

    # 3. Build StateGraph Pipeline
    builder = StateGraph(AgentState)

    builder.add_node(NodeName.PREP_PLANNER, prep_planner)
    builder.add_node(NodeName.PLANNER, run_planner_node)
    builder.add_node(NodeName.SYNC_PLANNER_OUTPUT, sync_planner_output)

    builder.add_node(NodeName.PREP_EVALUATOR, prep_evaluator)
    builder.add_node(NodeName.EVALUATOR, run_evaluator_node)
    builder.add_node(NodeName.PARSE_EVALUATOR_OUTPUT, parse_evaluator_output)

    builder.add_node(NodeName.INCREMENT_RETRY, increment_retry)

    # 4. Configure Edges
    builder.set_entry_point(NodeName.PREP_PLANNER)
    builder.add_edge(NodeName.PREP_PLANNER, NodeName.PLANNER)
    builder.add_edge(NodeName.PLANNER, NodeName.SYNC_PLANNER_OUTPUT)
    builder.add_edge(NodeName.SYNC_PLANNER_OUTPUT, NodeName.PREP_EVALUATOR)
    builder.add_edge(NodeName.PREP_EVALUATOR, NodeName.EVALUATOR)
    builder.add_edge(NodeName.EVALUATOR, NodeName.PARSE_EVALUATOR_OUTPUT)

    builder.add_conditional_edges(
        NodeName.PARSE_EVALUATOR_OUTPUT,
        replan_router,
        {
            NodeName.INCREMENT_RETRY: NodeName.INCREMENT_RETRY,
            END: END,
        },
    )
    builder.add_edge(NodeName.INCREMENT_RETRY, NodeName.PREP_PLANNER)

    return builder.compile(checkpointer=checkpointer)


async def stream_planner_graph(
    graph: CompiledStateGraph,
    input_data: Any,
    thread_id: str,
    version: str = "v2",
) -> AsyncIterator[dict[str, Any]]:
    """Invoke the compiled planner graph through stream, passing the planner thread ID."""
    from core.config import get_settings

    logger.info("planner_graph_stream_start", thread_id=thread_id)
    config = {
        "recursion_limit": get_settings().agent_recursion_limit,
        "configurable": {
            "thread_id": thread_id,
        },
    }

    async for event in graph.astream_events(
        input_data, config=config, version=version, subgraphs=True
    ):
        yield event
