export interface FormSection {
  key: string
  title: string
  help: string
}

export const organizationSections: FormSection[] = [
  ['identity', 'Organization identity', 'Name, website, and optional notification email.'],
  ['company_overview', 'Company overview', 'Description, mission, founding year, headquarters.'],
  ['industry', 'Industry', 'Primary industry, secondary industries, and sub-verticals.'],
  ['business_model', 'Business model', 'B2B/B2C/B2G and operating model.'],
  ['company_size', 'Company size', 'Employees, annual revenue, and years in business.'],
  ['target_markets', 'Target markets', 'Countries, regions, industries, and excluded markets.'],
  ['existing_customers', 'Existing customers', 'Typical customer profile and strongest industries.'],
  ['customer_segments', 'Customer segments', 'Primary, secondary, and avoided segments.'],
  ['brand_positioning', 'Brand positioning', 'Market position and positioning statement.'],
  ['unique_strengths', 'Unique strengths', 'Company-level competitive strengths.'],
  ['competitive_landscape', 'Competitive landscape', 'Competitors, differentiators, win/loss notes.'],
  ['sales_goals', 'Sales goals', 'Revenue targets, strategic industries, expansion markets.'],
  ['partnership_strategy', 'Partnership strategy', 'Direct, partner, reseller, and regional model.'],
  ['delivery_capability', 'Delivery capability', 'Geography, languages, support, implementation capacity.'],
  ['certifications_compliance', 'Certifications & compliance', 'Certifications, frameworks, residency.'],
  ['technology_expertise', 'Technology expertise', 'Cloud, languages, platforms, and tools.'],
  ['case_studies', 'Case studies', 'Customer type, challenge, outcome, and references.'],
  ['references', 'References', 'Logo clients, websites, and reference industries.'],
  ['pricing_position', 'Pricing position', 'Price band, contract size, competitive position.'],
  ['sales_process', 'Sales process', 'Stages, cycle length, and stakeholders.'],
  ['deal_constraints', 'Deal constraints', 'Minimum value, exclusions, geography, deal breakers.'],
].map(([key, title, help]) => ({ key, title, help }))

export const productSections: FormSection[] = [
  ['identity', 'Product identity', 'Product/service name and kind.'],
  ['product_overview', 'Product overview', 'One-sentence summary and offering scope.'],
  ['problem_solved', 'Problem solved', 'Primary pain, secondary pains, cost of inaction.'],
  ['value_proposition', 'Value proposition', 'Primary value and measurable outcomes.'],
  ['icp', 'Ideal customer profile', 'Industry, size, geography, type, maturity.'],
  ['buyer_personas', 'Buyer personas', 'Primary titles, buyers, evaluators, seniority.'],
  ['use_cases', 'Use cases', 'Trigger, scenario, and expected outcome.'],
  ['customer_triggers', 'Customer triggers', 'Events indicating current need.'],
  ['exclusion rules', 'Blacklist', 'Product-level exclusion rules.'],
  ['competitors', 'Competitors', 'Direct and indirect alternatives.'],
  ['differentiators', 'Differentiators', 'Why customers choose this offering.'],
  ['pricing', 'Pricing', 'Model, range, minimum, cycle, engagement.'],
  ['implementation', 'Implementation', 'Setup, onboarding, requirements, customer resources.'],
  ['integrations', 'Integrations', 'Must-have, nice-to-have, ecosystems.'],
  ['customer_success_stories', 'Customer success stories', 'At least five reference companies.'],
  ['compliance_restrictions', 'Compliance / restrictions', 'Regions, certifications, legal and technical limits.'],
  ['keywords', 'Keywords', 'Problem, category, technology, and role terms.'],
  ['signals', 'Signals', 'Public indicators of active need.'],
].map(([key, title, help]) => ({ key, title, help }))

export const strategySections: FormSection[] = [
  ['overview', 'Sales strategy overview', 'Name, description, and target narrative.'],
  ['target_company_profile', 'Target company profile', 'Types, characteristics, examples, keywords, pains.'],
  ['target_decision_makers', 'Target decision makers', 'Primary/secondary titles and seniority order.'],
  ['priority_industries', 'Priority industries', 'Primary, secondary, and deprioritized industries.'],
  ['priority_geographies', 'Priority geographies', 'Countries, regions, cities, remote and exclusions.'],
  ['company_size', 'Company size', 'Employee/revenue bands and segment tags.'],
  ['buying_signals', 'Buying signals', 'Selected and custom current signals.'],
  ['prospecting_strategy', 'Prospecting strategy', 'Sources and source-specific hints.'],
  ['outreach_strategy', 'Outreach strategy', 'Channels, cadence, and do-not-contact rules.'],
  ['messaging_hypotheses', 'Messaging hypotheses', 'Hooks, proof points, tone, guidance.'],
  ['qualification_criteria', 'Qualification criteria', 'Must-have, nice-to-have, confidence.'],
  ['blacklist_criteria', 'Blacklist criteria', 'Rules for skipping companies.'],
  ['prioritization_rules', 'Prioritization rules', 'Ordering and tie-break rules.'],
  ['competitor_targeting', 'Competitor targeting', 'Incumbents, switch triggers, exceptions.'],
  ['exclusion_rules', 'Exclusion rules', 'Companies, domains, industries, regions.'],
  ['experiments', 'Experiments', 'Hypothesis, variant, success criteria, notes.'],
  ['success_metrics', 'Success metrics', 'Operator-defined run targets.'],
  ['lessons_learned', 'Lessons learned', 'What worked and did not work.'],
  ['best_practices', 'Best practices', 'Repeatable agent/operator tactics.'],
  ['run_targets', 'Run targets', 'Target companies and fixed contacts per company.'],
].map(([key, title, help]) => ({ key, title, help }))

export const organizationTemplate: Record<string, unknown> = {
  company_overview: { description: '', mission: '', founded_year: null, headquarters: '' },
  industry: { primary: '', secondary: [], sub_verticals: [] },
  business_model: { types: [], description: '' },
  company_size: { employees: '', revenue_range: '', years_in_business: null },
  target_markets: { countries: [], regions: [], industries: [], excluded: [] },
  existing_customers: { typical_profile: '', strong_industries: [] },
  customer_segments: { primary: [], secondary: [], avoid: [] },
  brand_positioning: { position: '', statement: '' },
  unique_strengths: [],
  competitive_landscape: { competitors: [], differentiators: [], win_loss_notes: '' },
  sales_goals: { revenue_targets: '', strategic_industries: [], expansion_markets: [] },
  partnership_strategy: { model: '', regions: '', notes: '' },
  delivery_capability: { geography: [], languages: [], support_hours: '', implementation_capacity: '' },
  certifications_compliance: { certifications: [], frameworks: [], data_residency: '' },
  technology_expertise: { cloud: [], languages: [], platforms: [], tools: [] },
  case_studies: [{ title: '', customer_type: '', challenge: '', outcome: '', link: '' }],
  references: { clients: [{ name: '', website: '' }], industries: [] },
  pricing_position: { band: '', typical_contract_size: '', positioning_notes: '' },
  sales_process: { stages: [], cycle_length: '', stakeholders: [] },
  deal_constraints: {
    min_contract_value: '',
    preferred_industries: [],
    excluded_industries: [],
    geographic_limits: [],
    other: '',
  },
}

export const productTemplate: Record<string, unknown> = {
  product_overview: { summary: '', offering_scope: '' },
  problem_solved: { primary: '', secondary: [], cost_of_inaction: '' },
  value_proposition: { primary: '', outcomes: [] },
  icp: {
    industries: { primary: [], secondary: [], avoid: [] },
    company_size: { employees_min: null, employees_max: null, revenue_min: null, revenue_max: null },
    geography: { countries: [], regions: [], exclude_countries: [] },
    company_types: [],
    maturity: [],
  },
  buyer_personas: { primary_titles: [], economic_buyer: '', technical_evaluator: '', seniority: [] },
  use_cases: [{ name: '', trigger: '', outcome: '' }],
  customer_triggers: [],
  'exclusion rules': { rules: [], free_text: '' },
  competitors: [{ name: '', website: '', type: 'direct' }],
  differentiators: [],
  pricing: { model: '', typical_range: '', min_deal_size: '', sales_cycle: '', engagement_model: '' },
  implementation: { setup_effort: '', onboarding_duration: '', technical_requirements: [], customer_resources: [] },
  integrations: { must_have: [], nice_to_have: [], ecosystems: [] },
  customer_success_stories: [{ name: '', website: '', industry: '', why_they_bought: '', outcome: '' }],
  compliance_restrictions: { regions_blocked: [], certifications: [], legal_notes: '', technical_limits: [] },
  keywords: [],
  signals: [],
}

export const strategyTemplate: Record<string, unknown> = {
  overview: { name: '', description: '', target_companies_narrative: '' },
  target_company_profile: { company_types: [], characteristics: [], similar_companies: [], keywords: [], problems_they_should_have: [] },
  target_decision_makers: { primary_titles: [], secondary_titles: [], seniority_order: [], contact_buying_signals: [] },
  priority_industries: { primary: [], secondary: [], deprioritized: [] },
  priority_geographies: { countries: [], regions: [], cities: [], remote_only: false, exclude_countries: [] },
  company_size: { employees_min: null, employees_max: null, revenue_min: null, revenue_max: null, segments: [] },
  buying_signals: { selected: [], custom: [] },
  prospecting_strategy: { sources: [], source_hints: {} },
  outreach_strategy: { primary_channel: '', channels: [], sequence_notes: '', do_not_contact_rules: [] },
  messaging_hypotheses: { primary_hook: '', secondary_hooks: [], proof_points: [], tone: '', message_guidance: '' },
  qualification_criteria: { must_have: [], nice_to_have: [], min_confidence_hint: null },
  blacklist_criteria: { rules: [] },
  prioritization_rules: { rules: [] },
  competitor_targeting: { incumbents_to_target: [], switch_triggers: [], avoid_unless_scaling: [] },
  exclusion_rules: { companies: [], domains: [], industries: [], regions: [] },
  experiments: [{ hypothesis: '', variant: '', success_criteria: '', notes: '' }],
  success_metrics: { targets: [] },
  lessons_learned: { worked: [], did_not_work: [] },
  best_practices: [],
  run_targets: { target_companies: 0, contacts_per_company_default: 0 },
}
