"""add_thumbnail_url

Revision ID: 6fb9fe8ce9eb
Revises: 0003_brain_embeddings
Create Date: 2026-07-17 11:03:08.122724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb9fe8ce9eb'
down_revision: Union[str, None] = '0003_brain_embeddings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))

    with op.batch_alter_table('sales_strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_strategy', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
