"""add tool customization rules

Revision ID: adfe13762aa1
Revises: 6fb9fe8ce9eb
Create Date: 2026-07-17 12:30:52.906548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfe13762aa1'
down_revision: Union[str, None] = '6fb9fe8ce9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_customization_rule',
    sa.Column('tool_name_prefix', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=2048), nullable=False),
    sa.Column('request_color', sa.String(length=20), nullable=True),
    sa.Column('response_color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_name_prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_customization_rule')
    # ### end Alembic commands ###
